### PR TITLE
Update dependencies and dependencies workflow

### PR DESCRIPTION
**Pull request by lillythomas**
PR to update dependencies to cover all notebooks and handle the env set up approach.

### CODE REVIEW

**Comment by lillythomas** [comment]
@wildintellect can we update `.github/workflows/deploy.yml` to pip install from `book/requirements.txt` as well?

**Comment by wildintellect** [comment]
@lillythomas they could share the same requirements, however that could lead to significantly longer build times, and technically to build the book not all of them are required. Let's think about other approaches before deciding, cc: @chuckwondo 

If we wanted both we would just merge the book/requirements.txt back into the top level file.

**Comment by wildintellect** [comment]
@lillythomas so there's nothing inherently wrong with this PR, however I notice that the dependencies are fairly old versions. `geopandas` has `shapely` as a dependency so you shouldn't need to explicitly list it, however I'm wondering if you ran into an issue because the packages are several years old you needed to specify the dependency versions?

**Comment by lillythomas** [comment]
Shifted all dependencies to top level build seeing as a longer single build time is worthwhile for the convenience of using the notebooks in binder @wildintellect

**Review by wildintellect — APPROVED** [review]

**Pull request merged**
