### PR TITLE
Reduce scope of interactive plot example

### PR DESCRIPTION
**Pull request by lillythomas**
Reduces scope of example for interactive plotting to earthquake magnitudes in the last week within the state of California. Ideally, this reduces execution time for the website.

### CODE REVIEW

**Comment by wildintellect** [comment]
@lillythomas the notebook needs to be executed before saving and committing so that it includes the plot binary/html.

**Review by wildintellect — CHANGES_REQUESTED** [review]
Make sure to execute the cell and save the notebook with the output. Right now the plot is blank.

**Comment by lillythomas** [comment]
> Make sure to execute the cell and save the notebook with the output. Right now the plot is blank.

Done

**Review by wildintellect — APPROVED** [review]
Let's try it.

**Pull request merged**
